version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:8000"
    environment:
      MONGO_URI: "mongodb://mongodb:27017/lbms" # Update this with your MongoDB configuration
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
