version: "3.9"

services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db

  api:
    build: .
    ports:
      - 8000:8000
    environment:
      PORT: 8000
      DB: mongodb://mongo_db:27017/lbms
      JWT_SECRET: MY-ULTRA-SECRET-PASSWORD
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
